services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/nomad-hzb/beamline-image/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

plugins:
#   # We only include our schema here. Without the explicit include, all plugins will be
#   # loaded. Many build in plugins require more dependencies. Install nomad-lab[parsing]
#   # to make all default plugins work.
#
  entry_points:
    include: [
      "pynxtools.nomad.entrypoints:nexus_parser",
      "pynxtools.nomad.entrypoints:nexus_schema",
      "nomad_chemical_energy.schema_packages:hzb_catlab_package",
      "nomad_chemical_energy.parsers:hzb_catlab_parser",
      "nomad_chemical_energy.parsers:tfc_sputtering_parser",
      "nomad_chemical_energy.schema_packages:tfc_schema_package",
      ]
